Decompose Widget.renderRootOn() to facilitate overriding
foretagsplatsen/widgetjs pull request #185
Opened 2021-11-17 17:14 UTC by DamienCassou

With this decomposition, widgets can just override `_makeRootTagOn()`
when they want to control the root tag and not get "widgetjs-widget".

2022-02-28 11:10 UTC, BenjaminVanRyseghem requested changes
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem and @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx-0TVx9wGdQNTPXPEy:-Mx-0TW-71W4kYvEEW0H:b9mss3a) (no related file):*
I don't see the purpose of this, as you can override `renderOn` with the exact same result.

Can you please explain the reasoning behind this PR?

---


<!-- Sent from Reviewable.io -->

2022-02-28 13:37 UTC, DamienCassou reviewed
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx-0TVx9wGdQNTPXPEy:-Mx-Y2Ru2tX26rPaaTU3:b-x8kz2j) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

I don't see the purpose of this, as you can override `renderOn` with the exact same result.

Can you please explain the reasoning behind this PR?

</blockquote></details>

indeed. I tried to write an answer in the commit message. What do you think?

---


<!-- Sent from Reviewable.io -->

2022-03-01 08:25 UTC, BenjaminVanRyseghem approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx-0TVx9wGdQNTPXPEy:-Mx3_B_CEXrgFdPL6BUp:bubcfpz) (no related file):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

indeed. I tried to write an answer in the commit message. What do you think?
</blockquote></details>

I think that it's not super intuitive that the correct way (so far) out of the 3 you can do is the one named `_makeRootTagOn` where `renderOn` sounds a lot more like the place to be...

---
___
*[src/Widget2.js, line 349 at r2](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx3ZtbkCGnQSpG-AT6D:-Mx3ZtbkCGnQSpG-AT6E:b-fns9bi) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/19d2368f729785f5f4677cb31686a3496226cf55/src/Widget2.js#L349)):*
> ```JavaScript
> 
> 	_makeRootTagOn(html) {
> 		return html.tag("widgetjs-widget");
> ```

so if you set a custom id in an override, it will break as well? as your custom id will get overridden ...


<!-- Sent from Reviewable.io -->

2022-03-01 08:42 UTC, DamienCassou reviewed
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx-0TVx9wGdQNTPXPEy:-Mx3dGxpDVOUX82v3vzb:b4x02cu) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

I think that it's not super intuitive that the correct way (so far) out of the 3 you can do is the one named `_makeRootTagOn` where `renderOn` sounds a lot more like the place to be...
</blockquote></details>

ok. I'm closing the PR.

---
___
*[src/Widget2.js, line 349 at r2](https://reviewable.io/reviews/foretagsplatsen/widgetjs/185#-Mx3ZtbkCGnQSpG-AT6D:-Mx3dCkZ7oni-Oj2InFt:b-dp1jkm) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/19d2368f729785f5f4677cb31686a3496226cf55/src/Widget2.js#L349)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

so if you set a custom id in an override, it will break as well? as your custom id will get overridden ...
</blockquote></details>

you are right


<!-- Sent from Reviewable.io -->

2022-03-01 08:42 UTC, closed without merging